-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 10:56:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EmoGameDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EmoGameDB` ;

-- -----------------------------------------------------
-- Schema EmoGameDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EmoGameDB` DEFAULT CHARACTER SET utf8 ;
USE `EmoGameDB` ;

-- -----------------------------------------------------
-- Table `EmoGameDB`.`Therapist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Therapist` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Therapist` (
  `email` CHAR(25) NOT NULL,
  `password` CHAR(64) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Category` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(15) NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`Stimulus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Stimulus` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Stimulus` (
  `idStimulus` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(30) NOT NULL,
  `category` INT NOT NULL,
  `type` TINYINT NULL,
  `file_name` VARCHAR(100) NULL,
  PRIMARY KEY (`idStimulus`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `category_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`category`)
    REFERENCES `EmoGameDB`.`Category` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Game` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL,
  PRIMARY KEY (`idGame`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`GameStimulus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`GameStimulus` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`GameStimulus` (
  `codGame` INT NOT NULL,
  `codStimulus` INT NOT NULL,
  `duration` INT NOT NULL,
  `indexRow` INT NOT NULL,
  PRIMARY KEY (`codGame`, `codStimulus`, `indexRow`),
  INDEX `codStimulus_idx` (`codStimulus` ASC) VISIBLE,
  CONSTRAINT `codGame`
    FOREIGN KEY (`codGame`)
    REFERENCES `EmoGameDB`.`Game` (`idGame`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `codStimulus`
    FOREIGN KEY (`codStimulus`)
    REFERENCES `EmoGameDB`.`Stimulus` (`idStimulus`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `EmoGameDB`.`Therapist`
-- -----------------------------------------------------
START TRANSACTION;
USE `EmoGameDB`;
INSERT INTO `EmoGameDB`.`Therapist` (`email`, `password`) VALUES ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');

COMMIT;


-- -----------------------------------------------------
-- Data for table `EmoGameDB`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `EmoGameDB`;
INSERT INTO `EmoGameDB`.`Category` (`idCategory`, `name`) VALUES (1, 'happiness');
INSERT INTO `EmoGameDB`.`Category` (`idCategory`, `name`) VALUES (2, 'sadness');
INSERT INTO `EmoGameDB`.`Category` (`idCategory`, `name`) VALUES (3, 'angriness');

COMMIT;


-- -----------------------------------------------------
-- Data for table `EmoGameDB`.`Stimulus`
-- -----------------------------------------------------
START TRANSACTION;
USE `EmoGameDB`;
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (1, 'cat_and_dog', 1, 0, './stimuli/23aprezXZbu.png');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (2, 'rain_leaf', 2, 0, './stimuli/27b7268c31716ecfe19ceea5827567e0yHy8n.jpg');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (3, 'sad_robot', 2, 0, './stimuli/71nMCpy19ULmGUTI.jpg');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (4, 'sad_song', 2, 3, './stimuli/Emotional_Slow_Drama_Piano_Sound_EffectchrME.mp3');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (5, 'angry_fella', 3, 0, './stimuli/Health_Issue-1200x628dVkjW.jpg');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (6, 'happiness_image', 1, 0, './stimuli/mot-happiness-141984449Cr9Xx.jpg');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (7, 'angry_panda', 3, 1, './stimuli/Never_Say_No_to_Panda_-_OFFICE_zaWGi.mp4');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (8, 'happy_video', 1, 1, './stimuli/PharrellWilliams-Happy(Video)N5Vbk.mp4');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (9, 'happy_poetry', 1, 2, './stimuli/poesia_feliceJusAC.txt');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (10, 'rage_poetry', 3, 2, './stimuli/RabbiacanzoneEXOU3.txt');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (11, 'sad_poetry', 2, 2, './stimuli/VentunoMarzoVlNPW.txt');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (12, 'sad_image', 2, 0, '-/stimuli/w1600RHphs.png');

COMMIT;

