-- MySQL Script generated by MySQL Workbench
-- Fri Dec  2 17:18:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EmoGameDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EmoGameDB` ;

-- -----------------------------------------------------
-- Schema EmoGameDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EmoGameDB` DEFAULT CHARACTER SET utf8 ;
USE `EmoGameDB` ;

-- -----------------------------------------------------
-- Table `EmoGameDB`.`Therapist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Therapist` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Therapist` (
  `email` CHAR(25) NOT NULL,
  `password` CHAR(64) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Category` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(15) NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`Stimulus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Stimulus` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Stimulus` (
  `idStimulus` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(30) NOT NULL,
  `category` INT NOT NULL,
  `type` TINYINT NULL,
  `file_name` VARCHAR(100) NULL,
  PRIMARY KEY (`idStimulus`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `category_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`category`)
    REFERENCES `EmoGameDB`.`Category` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`Game` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL,
  PRIMARY KEY (`idGame`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmoGameDB`.`GameStimulus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmoGameDB`.`GameStimulus` ;

CREATE TABLE IF NOT EXISTS `EmoGameDB`.`GameStimulus` (
  `codGame` INT NOT NULL,
  `codStimulus` INT NOT NULL,
  `duration` INT NOT NULL,
  `indexRow` INT NOT NULL,
  PRIMARY KEY (`codGame`, `codStimulus`, `indexRow`),
  INDEX `codStimulus_idx` (`codStimulus` ASC) VISIBLE,
  CONSTRAINT `codGame`
    FOREIGN KEY (`codGame`)
    REFERENCES `EmoGameDB`.`Game` (`idGame`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `codStimulus`
    FOREIGN KEY (`codStimulus`)
    REFERENCES `EmoGameDB`.`Stimulus` (`idStimulus`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `EmoGameDB`.`Therapist`
-- -----------------------------------------------------
START TRANSACTION;
USE `EmoGameDB`;
INSERT INTO `EmoGameDB`.`Therapist` (`email`, `password`) VALUES ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');

COMMIT;


-- -----------------------------------------------------
-- Data for table `EmoGameDB`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `EmoGameDB`;
INSERT INTO `EmoGameDB`.`Category` (`idCategory`, `name`) VALUES (1, 'happiness');
INSERT INTO `EmoGameDB`.`Category` (`idCategory`, `name`) VALUES (2, 'sadness');

COMMIT;


-- -----------------------------------------------------
-- Data for table `EmoGameDB`.`Stimulus`
-- -----------------------------------------------------
START TRANSACTION;
USE `EmoGameDB`;
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (1, 'Stimulus1', 1, 0, './stimuli/example1.jpg');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (2, 'Stimulus2', 1, 0, './stimuli/example2.jpg');
INSERT INTO `EmoGameDB`.`Stimulus` (`idStimulus`, `name`, `category`, `type`, `file_name`) VALUES (3, 'Stimulus3', 2, 1, './stimuli/example3.mp4');

COMMIT;

